### ISSUE TITLE
v2.9.0 Doesn't Support E275

### ISSUE THREAD

**Issue by iwanpark** [PyCQA/pycodestyle#1088]
I've just updated `pycodestyle` from `v2.8.0` to `v2.9.0`.
And then my Flake8 stops working as follows.
It said `v2.9.0` doesn't support https://www.flake8rules.com/rules/E275.html.
Could you help me with this?

```
Traceback (most recent call last):
  File "/Users/iwan/kasa/kasa-api/.venv/lib/python3.8/site-packages/flake8/plugins/manager.py", line 157, in load_plugin
    self._load()
  File "/Users/iwan/kasa/kasa-api/.venv/lib/python3.8/site-packages/flake8/plugins/manager.py", line 134, in _load
    self._plugin = self.entry_point.load()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 79, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'pycodestyle' has no attribute 'missing_whitespace_after_import_keyword'
```

Just for your information,
```
$ pip list | grep flake
flake8                        3.9.2
flake8-commas                 2.1.0
flake8-isort                  3.0.1
pyflakes                      2.3.1
```

**Comment by asottile** [comment]
you're forcing an incompatible version of flake8 and pycodestyle -- they need to be updated in lockstep (5.x is the one version supporting latest pycodestyle)
