### ISSUE TITLE
Failed running unittest

### ISSUE THREAD

**Issue by chrysle** [PyCQA/pycodestyle#1130]
Running the unittest in a virtual environment as described in the [documentation](https://github.com/chrysle/pycodestyle/blob/main/CONTRIBUTING.rst#running-unittest) fails with a NameError because of an undefined variable: 
```
$ python setup.py test
/home/user/repos/pycodestyle/venv-pycodestyle/lib/python3.8/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
  warnings.warn(msg, warning_class)
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing pycodestyle.egg-info/PKG-INFO
writing dependency_links to pycodestyle.egg-info/dependency_links.txt
writing entry points to pycodestyle.egg-info/entry_points.txt
writing top-level names to pycodestyle.egg-info/top_level.txt
reading manifest file 'pycodestyle.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'testsuite'
no previously-included directories found matching 'docs/_build'
adding license file 'LICENSE'
writing manifest file 'pycodestyle.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    setup(
  File "/home/user/repos/pycodestyle/venv-pycodestyle/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/user/repos/pycodestyle/venv-pycodestyle/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/user/repos/pycodestyle/venv-pycodestyle/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/user/repos/pycodestyle/venv-pycodestyle/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/user/repos/pycodestyle/venv-pycodestyle/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/user/repos/pycodestyle/venv-pycodestyle/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/user/repos/pycodestyle/venv-pycodestyle/lib/python3.8/site-packages/setuptools/command/test.py", line 224, in run
    self.run_tests()
  File "/home/user/repos/pycodestyle/venv-pycodestyle/lib/python3.8/site-packages/setuptools/command/test.py", line 227, in run_tests
    test = unittest.main(
  File "/usr/lib/python3.8/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.8/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.8/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib/python3.8/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.8/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.8/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/usr/lib/python3.8/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/home/user/repos/pycodestyle/venv-pycodestyle/lib/python3.8/site-packages/setuptools/command/test.py", line 57, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/user/repos/pycodestyle/testsuite/E71.py", line 2, in <module>
    if res == None:
NameError: name 'res' is not defined
```
Also, it seems that `setup.py test` is to be deprecated, could it be dropped?  

I'm running Ubuntu 20.04.05 LTS.

**Comment by asottile** [comment]
that's not the supported way to run the test suite and there isn't an easy way to turn it off

**Comment by chrysle** [comment]
Then why is it included in the contribution guide?

**Comment by asottile** [comment]
oh didn't notice that. can probably just delete that
