### ISSUE TITLE
Setting up `max-line-lenght` in setup.cfg raises TypeError: unorderable types: int() > list()

### ISSUE THREAD

**Issue by pallotron** [PyCQA/pycodestyle#488]
Hi, I have setup flake8 via `setup.py`, and added a `[flake8]` section to `setup.cfg`, like below:

```
$ cat setup.cfg
[nosetests]
detailed-errors=1
with-coverage=1
cover-package=fbtftp
cover-erase=1
verbosity=2

[flake8]
max-line-length = 80
```

Running `python3 setup.py flake8` raises a `TypeError`.
See stacktrace below, `max_line_length` happens to be a list ( [80] ), rather than an integer.

```
$ python3 setup.py flake8
running flake8
Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    cmdclass={'test': NoseTestCommand},
  File "/usr/lib64/python3.3/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.3/distutils/dist.py", line 929, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.3/distutils/dist.py", line 948, in run_command
    cmd_obj.run()
  File "/home/pallotron/github/fbtftp/.eggs/flake8-2.5.4-py3.3.egg/flake8/main.py", line 139, in run
    report = flake8_style.check_files()
  File "/home/pallotron/github/fbtftp/.eggs/flake8-2.5.4-py3.3.egg/flake8/engine.py", line 181, in check_files
    return self._retry_serial(self._styleguide.check_files, paths=paths)
  File "/home/pallotron/github/fbtftp/.eggs/flake8-2.5.4-py3.3.egg/flake8/engine.py", line 172, in _retry_serial
    return func(*args, **kwargs)
  File "/home/pallotron/github/fbtftp/.eggs/pep8-1.7.0-py3.3.egg/pep8.py", line 1840, in check_files
    self.input_dir(path)
  File "/home/pallotron/github/fbtftp/.eggs/pep8-1.7.0-py3.3.egg/pep8.py", line 1876, in input_dir
    runner(os.path.join(root, filename))
  File "/home/pallotron/github/fbtftp/.eggs/flake8-2.5.4-py3.3.egg/flake8/engine.py", line 126, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/home/pallotron/github/fbtftp/.eggs/pep8-1.7.0-py3.3.egg/pep8.py", line 1582, in check_all
    for token in self.generate_tokens():
  File "/home/pallotron/github/fbtftp/.eggs/pep8-1.7.0-py3.3.egg/pep8.py", line 1534, in generate_tokens
    self.maybe_check_physical(token)
  File "/home/pallotron/github/fbtftp/.eggs/pep8-1.7.0-py3.3.egg/pep8.py", line 1544, in maybe_check_physical
    self.check_physical(token[4])
  File "/home/pallotron/github/fbtftp/.eggs/pep8-1.7.0-py3.3.egg/pep8.py", line 1441, in check_physical
    result = self.run_check(check, argument_names)
  File "/home/pallotron/github/fbtftp/.eggs/pep8-1.7.0-py3.3.egg/pep8.py", line 1429, in run_check
    return check(*arguments)
  File "/home/pallotron/github/fbtftp/.eggs/pep8-1.7.0-py3.3.egg/pep8.py", line 212, in maximum_line_length
    if length > max_line_length and not noqa(line):
TypeError: unorderable types: int() > list()
[Exit code 1 @ 08:27:40]
```

My pep8 version:

```
$ pip3 list | grep pep
pep8 (1.7.0)
```

**Comment by sigmavirus24** [comment]
I'm very certain this is actually [this bug](https://gitlab.com/pycqa/flake8/issues/121).

**Comment by pallotron** [comment]
thanks, it looks like it! any idea of when a new package will be available for pip installation?

**Comment by sigmavirus24** [comment]
I think I might try to get 2.6.0 out this week or next depending on how many other things go sideways outside of work.
