### ISSUE TITLE
Crash on triple quoted string with line continuation

### ISSUE THREAD

**Issue by Wilfred** [PyCQA/pycodestyle#713]
Given the file:

```python
foo = \
    """bar
"""
```

pycodestyle 2.3.1 crashes:

```
$ pycodestyle demo.py
Traceback (most recent call last):
  File "/users/is/whughes/pyenvs/research3/bin/pycodestyle", line 11, in <module>
    sys.exit(_main())
  File "/users/is/whughes/pyenvs/research3/lib/python2.7/site-packages/pycodestyle.py", line 2309, in _main
    report = style_guide.check_files()
  File "/users/is/whughes/pyenvs/research3/lib/python2.7/site-packages/pycodestyle.py", line 2010, in check_files
    runner(path)
  File "/users/is/whughes/pyenvs/research3/lib/python2.7/site-packages/pycodestyle.py", line 2022, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/users/is/whughes/pyenvs/research3/lib/python2.7/site-packages/pycodestyle.py", line 1785, in check_all
    self.check_logical()
  File "/users/is/whughes/pyenvs/research3/lib/python2.7/site-packages/pycodestyle.py", line 1663, in check_logical
    for offset, text in self.run_check(check, argument_names) or ():
  File "/users/is/whughes/pyenvs/research3/lib/python2.7/site-packages/pycodestyle.py", line 633, in continued_indentation
    rel_indent[end[0] - first_row] = rel_indent[row]
IndexError: list assignment index out of range
```

This looks like a regression on #388.

**Comment by sigmavirus24** [comment]
I genuinely can't reproduce this locally. 😕 I'm running this on Python 2 and Python 3 and cannot get it to crash. I'm on Python 2.7.14 and 3.6.3. What version of Python are you using?

**Comment by sigmavirus24** [comment]
Also worth noting that on #388 I couldn't reproduce this. I was running a different OS back then too.

**Comment by FichteFoll** [comment]
I can reproduce this on Arch with Python 3.6 and pycodestyle 2.3.1-

**Comment by gantsevdenis** [comment]
I can reproduce this with Python 3.5.2 and pycodestyle 2.3.1 on Linux Mint

**Comment by Wilfred** [comment]
I can reproduce this with Python 2.7.11 and pycodestyle 2.3.1 on CentOS 7.3.1611 (where I originally saw it) and on Python 2.7.13 and pycodestyle 2.3.1 on macOS 10.12.6.

However, I think the issue may relate to trailing newlines:

```
$ cat demo_with_newline.py
foo = \
    """bar
"""
$ pycodestyle demo_with_newline.py

$ cat demo_without_newline.py
foo = \
    """bar
"""$ pycodestyle demo_without_newline.py
Traceback (most recent call last):
  File "/usr/local/bin/pycodestyle", line 11, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python2.7/site-packages/pycodestyle.py", line 2309, in _main
    report = style_guide.check_files()
  File "/usr/local/lib/python2.7/site-packages/pycodestyle.py", line 2010, in check_files
    runner(path)
  File "/usr/local/lib/python2.7/site-packages/pycodestyle.py", line 2022, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/usr/local/lib/python2.7/site-packages/pycodestyle.py", line 1785, in check_all
    self.check_logical()
  File "/usr/local/lib/python2.7/site-packages/pycodestyle.py", line 1663, in check_logical
    for offset, text in self.run_check(check, argument_names) or ():
  File "/usr/local/lib/python2.7/site-packages/pycodestyle.py", line 633, in continued_indentation
    rel_indent[end[0] - first_row] = rel_indent[row]
IndexError: list assignment index out of range
```

**Comment by sigmavirus24** [comment]
That must be it! The trailing new-line is present in my test file and probably why it doesn't appear to me. Thanks for that @Wilfred! That's a solid lead.

**Comment by Barro** [comment]
I have also encountered this issue with files that do not have triple quotes in them. They just require any type of quote and an appropriate mix of backslashes and newlines:

```
$ printf '0\\\n"\\\n0' | python pycodestyle.py -
$ printf '0\\\n'\''\\\n0' | python pycodestyle.py -
```

Both of these commands lead into this stack backtrace:

```
Traceback (most recent call last):
  File "pycodestyle.py", line 2327, in <module>
    _main()
  File "pycodestyle.py", line 2309, in _main
    report = style_guide.check_files()
  File "pycodestyle.py", line 2010, in check_files
    runner(path)
  File "pycodestyle.py", line 2022, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "pycodestyle.py", line 1785, in check_all
    self.check_logical()
  File "pycodestyle.py", line 1663, in check_logical
    for offset, text in self.run_check(check, argument_names) or ():
  File "pycodestyle.py", line 633, in continued_indentation
    rel_indent[end[0] - first_row] = rel_indent[row]
IndexError: list assignment index out of range
```

Pycodestyle version 2.3.1 and Python version 2.7.14 (in Debian testing).

**Comment by asottile** [comment]
this appears to only be a problem in python2, I cannot reproduce it in python3


```console
$ printf '0\\\n'\''\\\n0' | venv2/bin/pycodestyle -
Traceback (most recent call last):
  File "venv2/bin/pycodestyle", line 8, in <module>
    sys.exit(_main())
  File "/tmp/x/venv2/lib/python2.7/site-packages/pycodestyle.py", line 2649, in _main
    report = style_guide.check_files()
  File "/tmp/x/venv2/lib/python2.7/site-packages/pycodestyle.py", line 2342, in check_files
    runner(path)
  File "/tmp/x/venv2/lib/python2.7/site-packages/pycodestyle.py", line 2354, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/tmp/x/venv2/lib/python2.7/site-packages/pycodestyle.py", line 2116, in check_all
    self.check_logical()
  File "/tmp/x/venv2/lib/python2.7/site-packages/pycodestyle.py", line 1998, in check_logical
    for offset, text in self.run_check(check, argument_names) or ():
  File "/tmp/x/venv2/lib/python2.7/site-packages/pycodestyle.py", line 733, in continued_indentation
    rel_indent[end[0] - first_row] = rel_indent[row]
IndexError: list assignment index out of range
```

**Comment by asottile** [comment]
#727 contains a similar case where continuation is implicit instead of explicit (due to triple-quoted strings)
