### ISSUE TITLE
pycodestyle 2.7.0 breaks flake8

### ISSUE THREAD

**Issue by bulletmark** [PyCQA/pycodestyle#983]
I update My Arch Linux system every day and today I had the following update:

````
2021-03-17 07:36:36 python-pycodestyle 2.6.0-3 -> 2.7.0-1
````

Now as of today, when I run `flake8` I get:
````
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 418, in run_check
self.processor.keyword_arguments_for(
File "/usr/lib/python3.9/site-packages/flake8/processor.py", line 251, in keyword_arguments_for
arguments[param] = getattr(self, param)
AttributeError: 'FileProcessor' object has no attribute 'indent_size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/flake8", line 33, in <module>
sys.exit(load_entry_point('flake8==3.8.4', 'console_scripts', 'flake8')())
File "/usr/lib/python3.9/site-packages/flake8/main/cli.py", line 22, in main
app.run(argv)
File "/usr/lib/python3.9/site-packages/flake8/main/application.py", line 363, in run
self._run(argv)
File "/usr/lib/python3.9/site-packages/flake8/main/application.py", line 351, in _run
self.run_checks()
File "/usr/lib/python3.9/site-packages/flake8/main/application.py", line 264, in run_checks
self.file_checker_manager.run()
File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 323, in run
self.run_serial()
File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 307, in run_serial
checker.run_checks()
File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 588, in run_checks
self.process_tokens()
File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 577, in process_tokens
self.handle_newline(token_type)
File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 612, in handle_newline
self.run_logical_checks()
File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 513, in run_logical_checks
results = self.run_check(plugin, logical_line=logical_line) or ()
File "/usr/lib/python3.9/site-packages/flake8/checker.py", line 423, in run_check
raise exceptions.PluginRequestedUnknownParameters(
flake8.exceptions.PluginRequestedUnknownParameters: "pycodestyle" requested unknown parameters causing 'FileProcessor' object has no attribute 'indent_size'
````
If I downgrade `python-pycodestyle` to `2.6.0-3` then it works normally.

**Comment by asottile** [comment]
you're attempting to use incompatible versions of flake8 with incompatible versions of pycodestyle

**Comment by sigmavirus24** [comment]
Please raise this bug with your archlinux packager as they're packaging things incorrectly. They should be upgrading Flake8 which had a release on (I believe) the same day or the day after

**Comment by bulletmark** [comment]
I did raise a bug there and the Arch Linux devs quickly released `flake8` 2.9.0.

I suggest that next time a breaking change is introduced it should be explicitly mentioned in the [release notice](https://pycodestyle.pycqa.org/en/latest/developer.html#id2).

**Comment by asottile** [comment]
it was not a breaking change.  flake8 carefully selects the version of pycodestyle to use and your package manager violated that

**Comment by bulletmark** [comment]
So you don't agree that this incompatibility should have been mentioned in the [pycodestyle  2.7.0 release notice](https://pycodestyle.pycqa.org/en/latest/developer.html#id2)?

**Comment by asottile** [comment]
correct

**Comment by sigmavirus24** [comment]
@bulletmark as Flake8 maintainers and pycodestyle maintainers this is not backwards incompatible. And pycodestyle does not need to declare incompatibilities with old versions of Flake8 when Flake8 explicitly declares what it supports (regardless of what package maintainers do to bypass that).

**Comment by avatar-lavventura** [comment]
> you're attempting to use incompatible versions of flake8 with incompatible versions of pycodestyle

Will we able to use it with the latest version of the `pycodestyle` in future or should we always stick with `pycodestyle==2.6.0-3`?

**Comment by asottile** [comment]
the latest versions work already today
